### ISSUE TITLE
Görsel Hata

### ISSUE THREAD

**Issue by thecsa** [needim/gider.im-pwa#34]
![Screenshot_7-11-2024_172312_app gider im](https://github.com/user-attachments/assets/245a0656-d682-4fcb-998b-e49cfdcb771d)

Bugün gelen güncellemeden sonra giriş ekranı bu hale geldi. Etiket alanı ekrana sığmıyor.

**Comment by needim** [comment]
Selam, bir görsel hata yok, #30 için bir güncelleme çıktım ve gider gelir tip seçimini tek el ile kullanılabilir hale gelmesi için aşağı yaklaştırdım. 

Rakamların üstündeki satır scroll edilebilir durumda.

**Comment by thecsa** [comment]
Farketmemiştim. Teşekkürler.
